export function initPerks(perkList: Perks) {
    perkList.Deathbound = { id: 'Deathbound', displayName: 'Deathbound', description: '', side: 'killer', teachableLevel: 40, character: 'The Executioner', characterIndex: 268435475, iconPath: 'UI/Icons/Perks/Wales/iconPerks_deathbound.png' };
    perkList.IronMaiden = { id: 'IronMaiden', displayName: 'Iron Maiden', description: '', side: 'killer', teachableLevel: 40, character: 'The Legion', characterIndex: 268435469, iconPath: 'UI/Icons/Perks/Kenya/iconPerks_ironMaiden.png' };
    perkList.Hex_Ruin = { id: 'Hex_Ruin', displayName: 'Hex: Ruin', description: '', side: 'killer', teachableLevel: 35, character: 'The Hag', characterIndex: 268435460, iconPath: 'UI/Icons/Perks/DLC3/iconPerks_ruin.png' };
    perkList.DeadMansSwitch = { id: 'DeadMansSwitch', displayName: 'Dead Man\'s Switch', description: '', side: 'killer', teachableLevel: 35, character: 'The Deathslinger', characterIndex: 268435474, iconPath: 'UI/Icons/Perks/Ukraine/iconPerks_deadManSwitch.png' };
    perkList.Babysitter = { id: 'Babysitter', displayName: 'Babysitter', description: '', side: 'survivor', teachableLevel: 30, character: 'Steve Harrington', characterIndex: 18, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_babySitter.png' };
    perkList.Open_Handed = { id: 'Open_Handed', displayName: 'Open-Handed', description: '', side: 'survivor', teachableLevel: 30, character: 'Ace Visconti', characterIndex: 6, iconPath: 'UI/Icons/Perks/DLC3/iconPerks_openHanded.png' };
    perkList.QuickQuiet = { id: 'QuickQuiet', displayName: 'Quick & Quiet', description: '', side: 'survivor', teachableLevel: 30, character: 'Meg Thomas', characterIndex: 1, iconPath: 'UI/Icons/Perks/iconPerks_quickAndQuiet.png' };
    perkList.DarkDevotion = { id: 'DarkDevotion', displayName: 'Dark Devotion', description: '', side: 'killer', teachableLevel: 40, character: 'The Plague', characterIndex: 268435470, iconPath: 'UI/Icons/Perks/Mali/iconPerks_darkDevotion.png' };
    perkList.SoulGuard = { id: 'SoulGuard', displayName: 'Soul Guard', description: '', side: 'survivor', teachableLevel: 30, character: 'Cheryl Mason', characterIndex: 21, iconPath: 'UI/Icons/Perks/Wales/iconPerks_soulGuard.png' };
    perkList.Technician = { id: 'Technician', displayName: 'Technician', description: '', side: 'survivor', teachableLevel: 30, character: 'Feng Min', characterIndex: 8, iconPath: 'UI/Icons/Perks/DLC4/iconPerks_technician.png' };
    perkList.MonitorAndAbuse = { id: 'MonitorAndAbuse', displayName: 'Monitor & Abuse', description: '', side: 'killer', teachableLevel: 35, character: 'The Doctor', characterIndex: 268435462, iconPath: 'UI/Icons/Perks/DLC4/iconPerks_monitorAndAbuse.png' };
    perkList.OverwhelmingPresence = { id: 'OverwhelmingPresence', displayName: 'Overwhelming Presence', description: '', side: 'killer', teachableLevel: 30, character: 'The Doctor', characterIndex: 268435462, iconPath: 'UI/Icons/Perks/DLC4/iconPerks_overwhelmingPresence.png' };
    perkList.ForThePeople = { id: 'ForThePeople', displayName: 'For the People', description: '', side: 'survivor', teachableLevel: 40, character: 'Zarina Kassir', characterIndex: 20, iconPath: 'UI/Icons/Perks/Ukraine/iconPerks_forThePeople.png' };
    perkList.Agitation = { id: 'Agitation', displayName: 'Agitation', description: '', side: 'killer', teachableLevel: 40, character: 'The Trapper', characterIndex: 268435456, iconPath: 'UI/Icons/Perks/iconPerks_agitation.png' };
    perkList.Plunderers_Instinct = { id: 'Plunderers_Instinct', displayName: 'Plunderer\'s Instinct', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_plunderersInstinct.png' };
    perkList.Tinkerer = { id: 'Tinkerer', displayName: 'Tinkerer', description: '', side: 'killer', teachableLevel: 40, character: 'The Hillbilly', characterIndex: 268435458, iconPath: 'UI/Icons/Perks/iconPerks_tinkerer.png' };
    perkList.Empathy = { id: 'Empathy', displayName: 'Empathy', description: '', side: 'survivor', teachableLevel: 30, character: 'Claudette Morel', characterIndex: 2, iconPath: 'UI/Icons/Perks/iconPerks_empathy.png' };
    perkList.FireUp = { id: 'FireUp', displayName: 'Fire Up', description: '', side: 'killer', teachableLevel: 30, character: 'The Nightmare', characterIndex: 268435465, iconPath: 'UI/Icons/Perks/England/iconPerks_fireUp.png' };
    perkList.BloodWarden = { id: 'BloodWarden', displayName: 'Blood Warden', description: '', side: 'killer', teachableLevel: 40, character: 'The Nightmare', characterIndex: 268435465, iconPath: 'UI/Icons/Perks/England/iconPerks_bloodWarden.png' };
    perkList.Prove_Thyself = { id: 'Prove_Thyself', displayName: 'Prove Thyself', description: '', side: 'survivor', teachableLevel: 35, character: 'Dwight Fairfield', characterIndex: 0, iconPath: 'UI/Icons/Perks/iconPerks_proveThyself.png' };
    perkList.Sprint_Burst = { id: 'Sprint_Burst', displayName: 'Sprint Burst', description: '', side: 'survivor', teachableLevel: 35, character: 'Meg Thomas', characterIndex: 1, iconPath: 'UI/Icons/Perks/iconPerks_sprintBurst.png' };
    perkList.Spine_Chill = { id: 'Spine_Chill', displayName: 'Spine Chill', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_spineChill.png' };
    perkList.Deja_Vu = { id: 'Deja_Vu', displayName: 'Déjà Vu', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_dejaVu.png' };
    perkList.Botany_Knowledge = { id: 'Botany_Knowledge', displayName: 'Botany Knowledge', description: '', side: 'survivor', teachableLevel: 35, character: 'Claudette Morel', characterIndex: 2, iconPath: 'UI/Icons/Perks/iconPerks_botanyKnowledge.png' };
    perkList.AnyMeansNecessary = { id: 'AnyMeansNecessary', displayName: 'Any Means Necessary', description: '', side: 'survivor', teachableLevel: 35, character: 'Yui Kimura', characterIndex: 19, iconPath: 'UI/Icons/Perks/Sweden/iconPerks_anyMeansNecessary.png' };
    perkList.WellMakeIt = { id: 'WellMakeIt', displayName: 'We\'ll Make It', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_wellMakeIt.png' };
    perkList.Unrelenting = { id: 'Unrelenting', displayName: 'Unrelenting', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_unrelenting.png' };
    perkList.Iron_Grasp = { id: 'Iron_Grasp', displayName: 'Iron Grasp', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_ironGrasp.png' };
    perkList.Monstrous_Shrine = { id: 'Monstrous_Shrine', displayName: 'Monstrous Shrine', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_monstrousShrine.png' };
    perkList.Lightweight = { id: 'Lightweight', displayName: 'Lightweight', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_lightweight.png' };
    perkList.Pharmacy = { id: 'Pharmacy', displayName: 'Pharmacy', description: '', side: 'survivor', teachableLevel: 35, character: 'Quentin Smith', characterIndex: 11, iconPath: 'UI/Icons/Perks/England/iconPerks_pharmacy.png' };
    perkList.Kindred = { id: 'Kindred', displayName: 'Kindred', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_kindred.png' };
    perkList.Sloppy_Butcher = { id: 'Sloppy_Butcher', displayName: 'Sloppy Butcher', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_sloppyButcher.png' };
    perkList.SecondWind = { id: 'SecondWind', displayName: 'Second Wind', description: '', side: 'survivor', teachableLevel: 40, character: 'Steve Harrington', characterIndex: 18, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_secondWind.png' };
    perkList.Nemesis = { id: 'Nemesis', displayName: 'Nemesis', description: '', side: 'killer', teachableLevel: 40, character: 'The Oni', characterIndex: 268435473, iconPath: 'UI/Icons/Perks/Sweden/iconPerks_nemesis.png' };
    perkList.Vigil = { id: 'Vigil', displayName: 'Vigil', description: '', side: 'survivor', teachableLevel: 40, character: 'Quentin Smith', characterIndex: 11, iconPath: 'UI/Icons/Perks/England/iconPerks_vigil.png' };
    perkList.Hex_Thrill_Of_The_Hunt = { id: 'Hex_Thrill_Of_The_Hunt', displayName: 'Hex: Thrill of the Hunt', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/DLC3/iconPerks_thrillOfTheHunt.png' };
    perkList.Bloodhound = { id: 'Bloodhound', displayName: 'Bloodhound', description: '', side: 'killer', teachableLevel: 35, character: 'The Wraith', characterIndex: 268435457, iconPath: 'UI/Icons/Perks/iconPerks_bloodhound.png' };
    perkList.Balanced_Landing = { id: 'Balanced_Landing', displayName: 'Balanced Landing', description: '', side: 'survivor', teachableLevel: 30, character: 'Nea Karlsson', characterIndex: 4, iconPath: 'UI/Icons/Perks/iconPerks_balancedLanding.png' };
    perkList.Dark_Sense = { id: 'Dark_Sense', displayName: 'Dark Sense', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_darkSense.png' };
    perkList.Shadowborn = { id: 'Shadowborn', displayName: 'Shadowborn', description: '', side: 'killer', teachableLevel: 40, character: 'The Wraith', characterIndex: 268435457, iconPath: 'UI/Icons/Perks/iconPerks_shadowborn.png' };
    perkList.ObjectOfObsession = { id: 'ObjectOfObsession', displayName: 'Object of Obsession', description: '', side: 'survivor', teachableLevel: 35, character: 'Laurie Strode', characterIndex: 5, iconPath: 'UI/Icons/Perks/DLC2/iconPerks_objectOfObsession.png' };
    perkList.Breakdown = { id: 'Breakdown', displayName: 'Breakdown', description: '', side: 'survivor', teachableLevel: 30, character: 'Jeff Johansen', characterIndex: 14, iconPath: 'UI/Icons/Perks/Kenya/iconPerks_breakdown.png' };
    perkList.ForcedPenance = { id: 'ForcedPenance', displayName: 'Forced Penance', description: '', side: 'killer', teachableLevel: 30, character: 'The Executioner', characterIndex: 268435475, iconPath: 'UI/Icons/Perks/Wales/iconPerks_forcedPenance.png' };
    perkList.Lithe = { id: 'Lithe', displayName: 'Lithe', description: '', side: 'survivor', teachableLevel: 35, character: 'Feng Min', characterIndex: 8, iconPath: 'UI/Icons/Perks/DLC4/iconPerks_lithe.png' };
    perkList.Lightborn = { id: 'Lightborn', displayName: 'Lightborn', description: '', side: 'killer', teachableLevel: 35, character: 'The Hillbilly', characterIndex: 268435458, iconPath: 'UI/Icons/Perks/iconPerks_lightborn.png' };
    perkList.Diversion = { id: 'Diversion', displayName: 'Diversion', description: '', side: 'survivor', teachableLevel: 30, character: 'Adam Francis', characterIndex: 13, iconPath: 'UI/Icons/Perks/Haiti/iconPerks_diversion.png' };
    perkList.Insidious = { id: 'Insidious', displayName: 'Insidious', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_insidious.png' };
    perkList.Rancor = { id: 'Rancor', displayName: 'Rancor', description: '', side: 'killer', teachableLevel: 40, character: 'The Spirit', characterIndex: 268435468, iconPath: 'UI/Icons/Perks/Haiti/iconPerks_hatred.png' };
    perkList.Dance_with_me = { id: 'Dance_with_me', displayName: 'Dance With Me', description: '', side: 'survivor', teachableLevel: 30, character: 'Kate Denson', characterIndex: 10, iconPath: 'UI/Icons/Perks/Kate/iconPerks_danceWithMe.png' };
    perkList.BorrowedTime = { id: 'BorrowedTime', displayName: 'Borrowed Time', description: '', side: 'survivor', teachableLevel: 35, character: 'William "Bill" Overbeck', characterIndex: 7, iconPath: 'UI/Icons/Perks/L4D/iconPerks_borrowedTime.png' };
    perkList.DeadHard = { id: 'DeadHard', displayName: 'Dead Hard', description: '', side: 'survivor', teachableLevel: 35, character: 'David King', characterIndex: 9, iconPath: 'UI/Icons/Perks/DLC5/iconPerks_DeadHard.png' };
    perkList.Saboteur = { id: 'Saboteur', displayName: 'Saboteur', description: '', side: 'survivor', teachableLevel: 40, character: 'Jake Park', characterIndex: 3, iconPath: 'UI/Icons/Perks/iconPerks_saboteur.png' };
    perkList.FranklinsLoss = { id: 'FranklinsLoss', displayName: 'Franklin\'s Demise', description: '', side: 'killer', teachableLevel: 40, character: 'The Leatherface', characterIndex: 268435464, iconPath: 'UI/Icons/Perks/Cannibal/iconPerks_franklinsLoss.png' };
    perkList.DetectivesHunch = { id: 'DetectivesHunch', displayName: 'Detective\'s Hunch', description: '', side: 'survivor', teachableLevel: 35, character: 'David Tapp', characterIndex: 12, iconPath: 'UI/Icons/Perks/Finland/iconPerks_detectivesHunch.png' };
    perkList.Hex_The_Third_Seal = { id: 'Hex_The_Third_Seal', displayName: 'Hex: The Third Seal', description: '', side: 'killer', teachableLevel: 30, character: 'The Hag', characterIndex: 268435460, iconPath: 'UI/Icons/Perks/DLC3/iconPerks_theThirdSeal.png' };
    perkList.Alert = { id: 'Alert', displayName: 'Alert', description: '', side: 'survivor', teachableLevel: 40, character: 'Feng Min', characterIndex: 8, iconPath: 'UI/Icons/Perks/DLC4/iconPerks_alert.png' };
    perkList.GeneratorOvercharge = { id: 'GeneratorOvercharge', displayName: 'Overcharge', description: '', side: 'killer', teachableLevel: 40, character: 'The Doctor', characterIndex: 268435462, iconPath: 'UI/Icons/Perks/DLC4/iconPerks_generatorOvercharge.png' };
    perkList.RememberMe = { id: 'RememberMe', displayName: 'Remember Me', description: '', side: 'killer', teachableLevel: 35, character: 'The Nightmare', characterIndex: 268435465, iconPath: 'UI/Icons/Perks/England/iconPerks_rememberMe.png' };
    perkList.InfectiousFright = { id: 'InfectiousFright', displayName: 'Infectious Fright', description: '', side: 'killer', teachableLevel: 35, character: 'The Plague', characterIndex: 268435470, iconPath: 'UI/Icons/Perks/Mali/iconPerks_infectiousFright.png' };
    perkList.Calm_Spirit = { id: 'Calm_Spirit', displayName: 'Calm Spirit', description: '', side: 'survivor', teachableLevel: 35, character: 'Jake Park', characterIndex: 3, iconPath: 'UI/Icons/Perks/iconPerks_calmSpirit.png' };
    perkList.Resilience = { id: 'Resilience', displayName: 'Resilience', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_resilience.png' };
    perkList.Bamboozle = { id: 'Bamboozle', displayName: 'Bamboozle', description: '', side: 'killer', teachableLevel: 30, character: 'The Clown', characterIndex: 268435467, iconPath: 'UI/Icons/Perks/Guam/iconPerks_bamboozle.png' };
    perkList.BoilOver = { id: 'BoilOver', displayName: 'Boil Over', description: '', side: 'survivor', teachableLevel: 40, character: 'Kate Denson', characterIndex: 10, iconPath: 'UI/Icons/Perks/Kate/iconPerks_boilOver.png' };
    perkList.SoleSurvivor = { id: 'SoleSurvivor', displayName: 'Sole Survivor', description: '', side: 'survivor', teachableLevel: 30, character: 'Laurie Strode', characterIndex: 5, iconPath: 'UI/Icons/Perks/DLC2/iconPerks_soleSurvivor.png' };
    perkList.LuckyBreak = { id: 'LuckyBreak', displayName: 'Lucky Break', description: '', side: 'survivor', teachableLevel: 30, character: 'Yui Kimura', characterIndex: 19, iconPath: 'UI/Icons/Perks/Sweden/iconPerks_luckyBreak.png' };
    perkList.CruelConfinement = { id: 'CruelConfinement', displayName: 'Cruel Limits', description: '', side: 'killer', teachableLevel: 40, character: 'The Demogorgon', characterIndex: 268435472, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_cruelConfinement.png' };
    perkList.BuckleUp = { id: 'BuckleUp', displayName: 'Buckle Up', description: '', side: 'survivor', teachableLevel: 35, character: 'Ash Williams', characterIndex: 16, iconPath: 'UI/Icons/Perks/Ash/iconPerks_buckleUp.png' };
    perkList.Distressing = { id: 'Distressing', displayName: 'Distressing', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_distressing.png' };
    perkList.Self_Care = { id: 'Self_Care', displayName: 'Self-Care', description: '', side: 'survivor', teachableLevel: 40, character: 'Claudette Morel', characterIndex: 2, iconPath: 'UI/Icons/Perks/iconPerks_selfCare.png' };
    perkList.WindowsOfOpportunity = { id: 'WindowsOfOpportunity', displayName: 'Windows of Opportunity', description: '', side: 'survivor', teachableLevel: 35, character: 'Kate Denson', characterIndex: 10, iconPath: 'UI/Icons/Perks/Kate/iconPerks_windowsOfOpportunity.png' };
    perkList.Deliverance = { id: 'Deliverance', displayName: 'Deliverance', description: '', side: 'survivor', teachableLevel: 35, character: 'Adam Francis', characterIndex: 13, iconPath: 'UI/Icons/Perks/Haiti/iconPerks_deliverance.png' };
    perkList.Small_Game = { id: 'Small_Game', displayName: 'Small Game', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_smallGame.png' };
    perkList.BeastOfPrey = { id: 'BeastOfPrey', displayName: 'Beast of Prey', description: '', side: 'killer', teachableLevel: 30, character: 'The Huntress', characterIndex: 268435463, iconPath: 'UI/Icons/Perks/DLC5/iconPerks_BeastOfPrey.png' };
    perkList.Hex_Devour_Hope = { id: 'Hex_Devour_Hope', displayName: 'Hex: Devour Hope', description: '', side: 'killer', teachableLevel: 40, character: 'The Hag', characterIndex: 268435460, iconPath: 'UI/Icons/Perks/DLC3/iconPerks_devourHope.png' };
    perkList.Gearhead = { id: 'Gearhead', displayName: 'Gearhead', description: '', side: 'killer', teachableLevel: 30, character: 'The Deathslinger', characterIndex: 268435474, iconPath: 'UI/Icons/Perks/Ukraine/iconPerks_gearHead.png' };
    perkList.Spies_From_The_Shadows = { id: 'Spies_From_The_Shadows', displayName: 'Spies from the Shadows', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_spiesFromTheShadows.png' };
    perkList.BloodEcho = { id: 'BloodEcho', displayName: 'Blood Echo', description: '', side: 'killer', teachableLevel: 35, character: 'The Oni', characterIndex: 268435473, iconPath: 'UI/Icons/Perks/Sweden/iconPerks_bloodEcho.png' };
    perkList.HangmansTrick = { id: 'HangmansTrick', displayName: 'Hangman\'s Trick', description: '', side: 'killer', teachableLevel: 30, character: 'The Pig', characterIndex: 268435466, iconPath: 'UI/Icons/Perks/Finland/iconPerks_hangmansTrick.png' };
    perkList.TheMettleOfMan = { id: 'TheMettleOfMan', displayName: 'Mettle of Man', description: '', side: 'survivor', teachableLevel: 40, character: 'Ash Williams', characterIndex: 16, iconPath: 'UI/Icons/Perks/Ash/iconPerks_mettleOfMan.png' };
    perkList.Play_With_Your_Food = { id: 'Play_With_Your_Food', displayName: 'Play with Your Food', description: '', side: 'killer', teachableLevel: 35, character: 'The Shape', characterIndex: 268435461, iconPath: 'UI/Icons/Perks/DLC2/iconPerks_playWithYourFood.png' };
    perkList.Hex_HauntedGround = { id: 'Hex_HauntedGround', displayName: 'Hex: Haunted Ground', description: '', side: 'killer', teachableLevel: 35, character: 'The Spirit', characterIndex: 268435468, iconPath: 'UI/Icons/Perks/Haiti/iconPerks_hauntedGround.png' };
    perkList.HexRetribution = { id: 'HexRetribution', displayName: 'Hex: Retribution', description: '', side: 'killer', teachableLevel: 40, character: 'The Deathslinger', characterIndex: 268435474, iconPath: 'UI/Icons/Perks/Ukraine/iconPerks_hexRetribution.png' };
    perkList.ThrillingTremors = { id: 'ThrillingTremors', displayName: 'Thrilling Tremors', description: '', side: 'killer', teachableLevel: 35, character: 'The Ghostface', characterIndex: 268435471, iconPath: 'UI/Icons/Perks/Oman/iconPerks_thrillingTremors.png' };
    perkList.Stridor = { id: 'Stridor', displayName: 'Stridor', description: '', side: 'killer', teachableLevel: 30, character: 'The Nurse', characterIndex: 268435459, iconPath: 'UI/Icons/Perks/iconPerks_stridor.png' };
    perkList.Deerstalker = { id: 'Deerstalker', displayName: 'Deerstalker', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_deerstalker.png' };
    perkList.pop_goes_the_weasel = { id: 'pop_goes_the_weasel', displayName: 'Pop Goes the Weasel', description: '', side: 'killer', teachableLevel: 40, character: 'The Clown', characterIndex: 268435467, iconPath: 'UI/Icons/Perks/Guam/iconPerks_popGoesTheWeasel.png' };
    perkList.Tenacity = { id: 'Tenacity', displayName: 'Tenacity', description: '', side: 'survivor', teachableLevel: 30, character: 'David Tapp', characterIndex: 12, iconPath: 'UI/Icons/Perks/Finland/iconPerks_tenacity.png' };
    perkList.Save_The_Best_For_Last = { id: 'Save_The_Best_For_Last', displayName: 'Save the Best for Last', description: '', side: 'killer', teachableLevel: 30, character: 'The Shape', characterIndex: 268435461, iconPath: 'UI/Icons/Perks/DLC2/iconPerks_saveTheBestForLast.png' };
    perkList.Bitter_Murmur = { id: 'Bitter_Murmur', displayName: 'Bitter Murmur', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_bitterMurmur.png' };
    perkList.RepressedAlliance = { id: 'RepressedAlliance', displayName: 'Repressed Alliance', description: '', side: 'survivor', teachableLevel: 40, character: 'Cheryl Mason', characterIndex: 21, iconPath: 'UI/Icons/Perks/Wales/iconPerks_repressedAlliance.png' };
    perkList.Poised = { id: 'Poised', displayName: 'Poised', description: '', side: 'survivor', teachableLevel: 35, character: 'Jane Romero', characterIndex: 15, iconPath: 'UI/Icons/Perks/Mali/iconPerks_poised.png' };
    perkList.Iron_Will = { id: 'Iron_Will', displayName: 'Iron Will', description: '', side: 'survivor', teachableLevel: 30, character: 'Jake Park', characterIndex: 3, iconPath: 'UI/Icons/Perks/iconPerks_ironWill.png' };
    perkList.Hex_HuntressLullaby = { id: 'Hex_HuntressLullaby', displayName: 'Hex: Huntress Lullaby', description: '', side: 'killer', teachableLevel: 40, character: 'The Huntress', characterIndex: 268435463, iconPath: 'UI/Icons/Perks/DLC5/iconPerks_HuntressLullaby.png' };
    perkList.Unnerving_Presence = { id: 'Unnerving_Presence', displayName: 'Unnerving Presence', description: '', side: 'killer', teachableLevel: 30, character: 'The Trapper', characterIndex: 268435456, iconPath: 'UI/Icons/Perks/iconPerks_unnervingPresence.png' };
    perkList.Camaraderie = { id: 'Camaraderie', displayName: 'Camaraderie', description: '', side: 'survivor', teachableLevel: 35, character: 'Steve Harrington', characterIndex: 18, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_camaraderie.png' };
    perkList.Predator = { id: 'Predator', displayName: 'Predator', description: '', side: 'killer', teachableLevel: 30, character: 'The Wraith', characterIndex: 268435457, iconPath: 'UI/Icons/Perks/iconPerks_predator.png' };
    perkList.Breakout = { id: 'Breakout', displayName: 'Breakout', description: '', side: 'survivor', teachableLevel: 40, character: 'Yui Kimura', characterIndex: 19, iconPath: 'UI/Icons/Perks/Sweden/iconPerks_breakout.png' };
    perkList.No_One_Left_Behind = { id: 'No_One_Left_Behind', displayName: 'No One Left Behind', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_noOneLeftBehind.png' };
    perkList.LeftBehind = { id: 'LeftBehind', displayName: 'Left Behind', description: '', side: 'survivor', teachableLevel: 30, character: 'William "Bill" Overbeck', characterIndex: 7, iconPath: 'UI/Icons/Perks/L4D/iconPerks_leftBehind.png' };
    perkList.This_Is_Not_Happening = { id: 'This_Is_Not_Happening', displayName: 'This Is Not Happening', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_thisIsNotHappening.png' };
    perkList.ImAllEars = { id: 'ImAllEars', displayName: 'I\'m All Ears', description: '', side: 'killer', teachableLevel: 30, character: 'The Ghostface', characterIndex: 268435471, iconPath: 'UI/Icons/Perks/Oman/iconPerks_imAllEars.png' };
    perkList.BetterTogether = { id: 'BetterTogether', displayName: 'Better Together', description: '', side: 'survivor', teachableLevel: 30, character: 'Nancy Wheeler', characterIndex: 17, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_betterTogether.png' };
    perkList.DecisiveStrike = { id: 'DecisiveStrike', displayName: 'Decisive Strike', description: '', side: 'survivor', teachableLevel: 40, character: 'Laurie Strode', characterIndex: 5, iconPath: 'UI/Icons/Perks/DLC2/iconPerks_decisiveStrike.png' };
    perkList.Surge = { id: 'Surge', displayName: 'Surge', description: '', side: 'killer', teachableLevel: 30, character: 'The Demogorgon', characterIndex: 268435472, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_surge.png' };
    perkList.StakeOut = { id: 'StakeOut', displayName: 'Stake Out', description: '', side: 'survivor', teachableLevel: 40, character: 'David Tapp', characterIndex: 12, iconPath: 'UI/Icons/Perks/Finland/iconPerks_stakeOut.png' };
    perkList.NurseCalling = { id: 'NurseCalling', displayName: 'A Nurse\'s Calling', description: '', side: 'killer', teachableLevel: 40, character: 'The Nurse', characterIndex: 268435459, iconPath: 'UI/Icons/Perks/iconPerks_aNursesCalling.png' };
    perkList.BloodPact = { id: 'BloodPact', displayName: 'Blood Pact', description: '', side: 'survivor', teachableLevel: 35, character: 'Cheryl Mason', characterIndex: 21, iconPath: 'UI/Icons/Perks/Wales/iconPerks_bloodPact.png' };
    perkList.ZanshinTactics = { id: 'ZanshinTactics', displayName: 'Zanshin Tactics', description: '', side: 'killer', teachableLevel: 30, character: 'The Oni', characterIndex: 268435473, iconPath: 'UI/Icons/Perks/Sweden/iconPerks_zanshinTactics.png' };
    perkList.HeadOn = { id: 'HeadOn', displayName: 'Head On', description: '', side: 'survivor', teachableLevel: 40, character: 'Jane Romero', characterIndex: 15, iconPath: 'UI/Icons/Perks/Mali/iconPerks_headOn.png' };
    perkList.Autodidact = { id: 'Autodidact', displayName: 'Autodidact', description: '', side: 'survivor', teachableLevel: 40, character: 'Adam Francis', characterIndex: 13, iconPath: 'UI/Icons/Perks/Haiti/iconPerks_autodidact.png' };
    perkList.RedHerring = { id: 'RedHerring', displayName: 'Red Herring', description: '', side: 'survivor', teachableLevel: 35, character: 'Zarina Kassir', characterIndex: 20, iconPath: 'UI/Icons/Perks/Ukraine/iconPerks_redHerring.png' };
    perkList.Enduring = { id: 'Enduring', displayName: 'Enduring', description: '', side: 'killer', teachableLevel: 30, character: 'The Hillbilly', characterIndex: 268435458, iconPath: 'UI/Icons/Perks/iconPerks_enduring.png' };
    perkList.Up_The_Ante = { id: 'Up_The_Ante', displayName: 'Up the Ante', description: '', side: 'survivor', teachableLevel: 35, character: 'Ace Visconti', characterIndex: 6, iconPath: 'UI/Icons/Perks/DLC3/iconPerks_upTheAnte.png' };
    perkList.Adrenaline = { id: 'Adrenaline', displayName: 'Adrenaline', description: '', side: 'survivor', teachableLevel: 40, character: 'Meg Thomas', characterIndex: 1, iconPath: 'UI/Icons/Perks/iconPerks_adrenaline.png' };
    perkList.Mindbreaker = { id: 'Mindbreaker', displayName: 'Mindbreaker', description: '', side: 'killer', teachableLevel: 35, character: 'The Demogorgon', characterIndex: 268435472, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_mindBreaker.png' };
    perkList.SelfSufficient = { id: 'SelfSufficient', displayName: 'Unbreakable', description: '', side: 'survivor', teachableLevel: 40, character: 'William "Bill" Overbeck', characterIndex: 7, iconPath: 'UI/Icons/Perks/L4D/iconPerks_unbreakable.png' };
    perkList.Distortion = { id: 'Distortion', displayName: 'Distortion', description: '', side: 'survivor', teachableLevel: 40, character: 'Jeff Johansen', characterIndex: 14, iconPath: 'UI/Icons/Perks/Kenya/iconPerks_distortion.png' };
    perkList.InnerStrength = { id: 'InnerStrength', displayName: 'Inner Strength', description: '', side: 'survivor', teachableLevel: 40, character: 'Nancy Wheeler', characterIndex: 17, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_innerStrength.png' };
    perkList.WereGonnaLiveForever = { id: 'WereGonnaLiveForever', displayName: 'We\'re Gonna Live Forever', description: '', side: 'survivor', teachableLevel: 30, character: 'David King', characterIndex: 9, iconPath: 'UI/Icons/Perks/DLC5/iconPerks_WereGonnaLiveForever.png' };
    perkList.Premonition = { id: 'Premonition', displayName: 'Premonition', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_premonition.png' };
    perkList.FlipFlop = { id: 'FlipFlop', displayName: 'Flip-Flop', description: '', side: 'survivor', teachableLevel: 30, character: 'Ash Williams', characterIndex: 16, iconPath: 'UI/Icons/Perks/Ash/iconPerks_flipFlop.png' };
    perkList.Ace_In_The_Hole = { id: 'Ace_In_The_Hole', displayName: 'Ace in the Hole', description: '', side: 'survivor', teachableLevel: 40, character: 'Ace Visconti', characterIndex: 6, iconPath: 'UI/Icons/Perks/DLC3/iconPerks_aceInTheHole.png' };
    perkList.Leader = { id: 'Leader', displayName: 'Leader', description: '', side: 'survivor', teachableLevel: 40, character: 'Dwight Fairfield', characterIndex: 0, iconPath: 'UI/Icons/Perks/iconPerks_leader.png' };
    perkList.Surveillance = { id: 'Surveillance', displayName: 'Surveillance', description: '', side: 'killer', teachableLevel: 35, character: 'The Pig', characterIndex: 268435466, iconPath: 'UI/Icons/Perks/Finland/iconPerks_surveillance.png' };
    perkList.FurtiveChase = { id: 'FurtiveChase', displayName: 'Furtive Chase', description: '', side: 'killer', teachableLevel: 40, character: 'The Ghostface', characterIndex: 268435471, iconPath: 'UI/Icons/Perks/Oman/iconPerks_furtiveChase.png' };
    perkList.MadGrit = { id: 'MadGrit', displayName: 'Mad Grit', description: '', side: 'killer', teachableLevel: 35, character: 'The Legion', characterIndex: 268435469, iconPath: 'UI/Icons/Perks/Kenya/iconPerks_madGrit.png' };
    perkList.InTheDark = { id: 'InTheDark', displayName: 'Knock Out', description: '', side: 'killer', teachableLevel: 30, character: 'The Leatherface', characterIndex: 268435464, iconPath: 'UI/Icons/Perks/Cannibal/iconPerks_knockOut.png' };
    perkList.TrailofTorment = { id: 'TrailofTorment', displayName: 'Trail of Torment', description: '', side: 'killer', teachableLevel: 35, character: 'The Executioner', characterIndex: 268435475, iconPath: 'UI/Icons/Perks/Wales/iconPerks_trailOfTorment.png' };
    perkList.Hope = { id: 'Hope', displayName: 'Hope', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_hope.png' };
    perkList.Solidarity = { id: 'Solidarity', displayName: 'Solidarity', description: '', side: 'survivor', teachableLevel: 30, character: 'Jane Romero', characterIndex: 15, iconPath: 'UI/Icons/Perks/Mali/iconPerks_solidarity.png' };
    perkList.Urban_Evasion = { id: 'Urban_Evasion', displayName: 'Urban Evasion', description: '', side: 'survivor', teachableLevel: 35, character: 'Nea Karlsson', characterIndex: 4, iconPath: 'UI/Icons/Perks/iconPerks_urbanEvasion.png' };
    perkList.Aftercare = { id: 'Aftercare', displayName: 'Aftercare', description: '', side: 'survivor', teachableLevel: 35, character: 'Jeff Johansen', characterIndex: 14, iconPath: 'UI/Icons/Perks/Kenya/iconPerks_aftercare.png' };
    perkList.Brutal_Strength = { id: 'Brutal_Strength', displayName: 'Brutal Strength', description: '', side: 'killer', teachableLevel: 35, character: 'The Trapper', characterIndex: 268435456, iconPath: 'UI/Icons/Perks/iconPerks_brutalStrength.png' };
    perkList.NoMither = { id: 'NoMither', displayName: 'No Mither', description: '', side: 'survivor', teachableLevel: 40, character: 'David King', characterIndex: 9, iconPath: 'UI/Icons/Perks/DLC5/iconPerks_NoMither.png' };
    perkList.WakeUp = { id: 'WakeUp', displayName: 'Wake Up!', description: '', side: 'survivor', teachableLevel: 30, character: 'Quentin Smith', characterIndex: 11, iconPath: 'UI/Icons/Perks/England/iconPerks_wakeUp.png' };
    perkList.Slippery_Meat = { id: 'Slippery_Meat', displayName: 'Slippery Meat', description: '', side: 'survivor', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_slipperyMeat.png' };
    perkList.Fixated = { id: 'Fixated', displayName: 'Fixated', description: '', side: 'survivor', teachableLevel: 35, character: 'Nancy Wheeler', characterIndex: 17, iconPath: 'UI/Icons/Perks/Qatar/iconPerks_fixated.png' };
    perkList.Streetwise = { id: 'Streetwise', displayName: 'Streetwise', description: '', side: 'survivor', teachableLevel: 40, character: 'Nea Karlsson', characterIndex: 4, iconPath: 'UI/Icons/Perks/iconPerks_streetwise.png' };
    perkList.Bond = { id: 'Bond', displayName: 'Bond', description: '', side: 'survivor', teachableLevel: 30, character: 'Dwight Fairfield', characterIndex: 0, iconPath: 'UI/Icons/Perks/iconPerks_bond.png' };
    perkList.Thanatophobia = { id: 'Thanatophobia', displayName: 'Thanatophobia', description: '', side: 'killer', teachableLevel: 35, character: 'The Nurse', characterIndex: 268435459, iconPath: 'UI/Icons/Perks/iconPerks_thatanophobia.png' };
    perkList.Coulrophobia = { id: 'Coulrophobia', displayName: 'Coulrophobia', description: '', side: 'killer', teachableLevel: 35, character: 'The Clown', characterIndex: 268435467, iconPath: 'UI/Icons/Perks/Guam/iconPerks_coulrophobia.png' };
    perkList.Whispers = { id: 'Whispers', displayName: 'Whispers', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_whispers.png' };
    perkList.BBQAndChilli = { id: 'BBQAndChilli', displayName: 'Barbecue & Chilli', description: '', side: 'killer', teachableLevel: 35, character: 'The Leatherface', characterIndex: 268435464, iconPath: 'UI/Icons/Perks/Cannibal/iconPerks_BBQAndChili.png' };
    perkList.Discordance = { id: 'Discordance', displayName: 'Discordance', description: '', side: 'killer', teachableLevel: 30, character: 'The Legion', characterIndex: 268435469, iconPath: 'UI/Icons/Perks/Kenya/iconPerks_discordance.png' };
    perkList.SpiritFury = { id: 'SpiritFury', displayName: 'Spirit Fury', description: '', side: 'killer', teachableLevel: 30, character: 'The Spirit', characterIndex: 268435468, iconPath: 'UI/Icons/Perks/Haiti/iconPerks_spiritFury.png' };
    perkList.CorruptIntervention = { id: 'CorruptIntervention', displayName: 'Corrupt Intervention', description: '', side: 'killer', teachableLevel: 30, character: 'The Plague', characterIndex: 268435470, iconPath: 'UI/Icons/Perks/Mali/iconPerks_corruptIntervention.png' };
    perkList.No_One_Escapes_Death = { id: 'No_One_Escapes_Death', displayName: 'Hex: No One Escapes Death', description: '', side: 'killer', teachableLevel: -1, character: 'Common', characterIndex: -1, iconPath: 'UI/Icons/Perks/iconPerks_noOneEscapesDeath.png' };
    perkList.OffTheRecord = { id: 'OffTheRecord', displayName: 'Off the Record', description: '', side: 'survivor', teachableLevel: 30, character: 'Zarina Kassir', characterIndex: 20, iconPath: 'UI/Icons/Perks/Ukraine/iconPerks_offTheRecord.png' };
    perkList.MakeYourChoice = { id: 'MakeYourChoice', displayName: 'Make Your Choice', description: '', side: 'killer', teachableLevel: 40, character: 'The Pig', characterIndex: 268435466, iconPath: 'UI/Icons/Perks/Finland/iconPerks_makeYourChoice.png' };
    perkList.Dying_Light = { id: 'Dying_Light', displayName: 'Dying Light', description: '', side: 'killer', teachableLevel: 40, character: 'The Shape', characterIndex: 268435461, iconPath: 'UI/Icons/Perks/DLC2/iconPerks_dyingLight.png' };
    perkList.TerritorialImperative = { id: 'TerritorialImperative', displayName: 'Territorial Imperative', description: '', side: 'killer', teachableLevel: 35, character: 'The Huntress', characterIndex: 268435463, iconPath: 'UI/Icons/Perks/DLC5/iconPerks_TerritorialImperative.png' };
    perkList.Hex_Undying = { id: 'Hex_Undying', displayName: 'Hex: Undying', description: '', side: 'killer', teachableLevel: 40, character: 'The Blight', characterIndex: 268435476, iconPath: 'UI/Icons/Perks/Yemen/iconPerks_hexUndying.png' };
    perkList.Hex_Blood_Favor = { id: 'Hex_Blood_Favor', displayName: 'Hex: Blood Favour', description: '', side: 'killer', teachableLevel: 35, character: 'The Blight', characterIndex: 268435476, iconPath: 'UI/Icons/Perks/Yemen/iconPerks_hexBloodFavor.png' };
    perkList.Dragons_Grip = { id: 'Hex_Undying', displayName: 'Dragon\'s Grip', description: '', side: 'killer', teachableLevel: 30, character: 'The Blight', characterIndex: 268435476, iconPath: 'UI/Icons/Perks/Yemen/iconPerks_dragonsGrip.png' };
    perkList.Visionary = { id: 'Visionary', displayName: 'Visionary', description: '', side: 'survivor', teachableLevel: 30, character: 'Felix Richter', characterIndex: 23, iconPath: 'UI/Icons/Perks/Yemen/iconPerks_visionary.png' };
    perkList.Desperate_Measures = { id: 'Desperate_Measures', displayName: 'Desperate Measures', description: '', side: 'survivor', teachableLevel: 35, character: 'Felix Richter', characterIndex: 23, iconPath: 'UI/Icons/Perks/Yemen/iconPerks_desperateMeasures.png' };
    perkList.Built_To_Last = { id: 'Built_To_Last', displayName: 'Built to Last', description: '', side: 'survivor', teachableLevel: 40, character: 'Felix Richter', characterIndex: 23, iconPath: 'UI/Icons/Perks/Yemen/iconPerks_builtToLast.png' };

    return perkList;
}

export interface Perks {
	Deathbound: Perk;
	IronMaiden: Perk;
	Hex_Ruin: Perk;
	DeadMansSwitch: Perk;
	Babysitter: Perk;
	Open_Handed: Perk;
	QuickQuiet: Perk;
	DarkDevotion: Perk;
	SoulGuard: Perk;
	Technician: Perk;
	MonitorAndAbuse: Perk;
	OverwhelmingPresence: Perk;
	ForThePeople: Perk;
	Agitation: Perk;
	Plunderers_Instinct: Perk;
	Tinkerer: Perk;
	Empathy: Perk;
	FireUp: Perk;
	BloodWarden: Perk;
	Prove_Thyself: Perk;
	Sprint_Burst: Perk;
	Spine_Chill: Perk;
	Deja_Vu: Perk;
	Botany_Knowledge: Perk;
	AnyMeansNecessary: Perk;
	WellMakeIt: Perk;
	Unrelenting: Perk;
	Iron_Grasp: Perk;
	Monstrous_Shrine: Perk;
	Lightweight: Perk;
	Pharmacy: Perk;
	Kindred: Perk;
	Sloppy_Butcher: Perk;
	SecondWind: Perk;
	Nemesis: Perk;
	Vigil: Perk;
	Hex_Thrill_Of_The_Hunt: Perk;
	Bloodhound: Perk;
	Balanced_Landing: Perk;
	Dark_Sense: Perk;
	Shadowborn: Perk;
	ObjectOfObsession: Perk;
	Breakdown: Perk;
	ForcedPenance: Perk;
	Lithe: Perk;
	Lightborn: Perk;
	Diversion: Perk;
	Insidious: Perk;
	Rancor: Perk;
	Dance_with_me: Perk;
	BorrowedTime: Perk;
	DeadHard: Perk;
	Saboteur: Perk;
	FranklinsLoss: Perk;
	DetectivesHunch: Perk;
	Hex_The_Third_Seal: Perk;
	Alert: Perk;
	GeneratorOvercharge: Perk;
	RememberMe: Perk;
	InfectiousFright: Perk;
	Calm_Spirit: Perk;
	Resilience: Perk;
	Bamboozle: Perk;
	BoilOver: Perk;
	SoleSurvivor: Perk;
	LuckyBreak: Perk;
	CruelConfinement: Perk;
	BuckleUp: Perk;
	Distressing: Perk;
	Self_Care: Perk;
	WindowsOfOpportunity: Perk;
	Deliverance: Perk;
	Small_Game: Perk;
	BeastOfPrey: Perk;
	Hex_Devour_Hope: Perk;
	Gearhead: Perk;
	Spies_From_The_Shadows: Perk;
	BloodEcho: Perk;
	HangmansTrick: Perk;
	TheMettleOfMan: Perk;
	Play_With_Your_Food: Perk;
	Hex_HauntedGround: Perk;
	HexRetribution: Perk;
	ThrillingTremors: Perk;
	Stridor: Perk;
	Deerstalker: Perk;
	pop_goes_the_weasel: Perk;
	Tenacity: Perk;
	Last_Standing: Perk;
	Save_The_Best_For_Last: Perk;
	Bitter_Murmur: Perk;
	RepressedAlliance: Perk;
	Poised: Perk;
	Iron_Will: Perk;
	Hex_HuntressLullaby: Perk;
	Unnerving_Presence: Perk;
	Camaraderie: Perk;
	Predator: Perk;
	Breakout: Perk;
	No_One_Left_Behind: Perk;
	LeftBehind: Perk;
	This_Is_Not_Happening: Perk;
	ImAllEars: Perk;
	BetterTogether: Perk;
	DecisiveStrike: Perk;
	Surge: Perk;
	StakeOut: Perk;
	NurseCalling: Perk;
	BloodPact: Perk;
	ZanshinTactics: Perk;
	HeadOn: Perk;
	Autodidact: Perk;
	RedHerring: Perk;
	Enduring: Perk;
	Up_The_Ante: Perk;
	Adrenaline: Perk;
	Mindbreaker: Perk;
	SelfSufficient: Perk;
	Distortion: Perk;
	InnerStrength: Perk;
	WereGonnaLiveForever: Perk;
	Premonition: Perk;
	FlipFlop: Perk;
	Ace_In_The_Hole: Perk;
	Leader: Perk;
	Surveillance: Perk;
	FurtiveChase: Perk;
	MadGrit: Perk;
	InTheDark: Perk;
	TrailofTorment: Perk;
	Hope: Perk;
	Solidarity: Perk;
	Urban_Evasion: Perk;
	Aftercare: Perk;
	Brutal_Strength: Perk;
	NoMither: Perk;
	WakeUp: Perk;
	Slippery_Meat: Perk;
	Fixated: Perk;
	Streetwise: Perk;
	Bond: Perk;
	Thanatophobia: Perk;
	Coulrophobia: Perk;
	Whispers: Perk;
	BBQAndChilli: Perk;
	Discordance: Perk;
	SpiritFury: Perk;
	CorruptIntervention: Perk;
	No_One_Escapes_Death: Perk;
	OffTheRecord: Perk;
	MakeYourChoice: Perk;
	Dying_Light: Perk;
    TerritorialImperative: Perk;
    Hex_Undying: Perk;
    Hex_Blood_Favor: Perk;
    Dragons_Grip: Perk;
    Visionary: Perk;
    Desperate_Measures: Perk;
    Built_To_Last: Perk;
}

export interface Perk {
	id: string;
	displayName: string;
    description: string;
    side: string;
	teachableLevel: number;
	character: string;
	characterIndex: number;
	iconPath: string;
}
